name: "CI"
on:
  push:
    branches:
      - 'main'
    tags:
      - ''
  pull_request:
    branches:
      - '*'
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: golangci-lint
        run:
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.53.3
          golangci-lint run ./... --out-format=github-actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Install minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
          sudo dpkg -i minikube_latest_amd64.deb

      - name: Set up minikube environment
        run: |
          minikube start

      - name: Create Nebula Graph Cluster
        run: |
          # add helm repo
          helm repo add nebula-operator https://vesoft-inc.github.io/nebula-operator/charts
          # install nebula-operator
          helm install --create-namespace  nebula-operator nebula-operator/nebula-operator --namespace=nebula-operator-system --version=1.4.2
          # wait for nebula-operator ready
          kubectl wait --for=condition=available deployment/nebula-operator-controller-manager-deployment --timeout=600s -n nebula-operator-system
          kubectl apply -f example.yaml
          # wait for nebula graph cluster ready
          kubectl wait --for=condition=Ready nebulacluster/nebula --timeout=600s

      - name: Go Code Test
        run: |
          go mod tidy
          go test ./... -race
